### ISSUE TITLE
Example command "plip -i 1vsn -yv" is not working

### ISSUE THREAD

**Issue by oliserand** [ssalentin/plip#30]
$plip -i 1vsn -yv
...
Checking status of PDB ID 1vsn ... entry is up to date.
Downloading file from PDB ... file downloaded as ./1vsn.pdb
...
PDB structure successfully read.
Analyzing one ligand...
...
  Contains 2 aromatic ring(s).
Traceback (most recent call last):
  File "/home/user/bin/source/pliptool/plip/plipcmd", line 306, in <module>
    main(expanded_path, arguments.pdbid)  # Start main script
  File "/home/user/bin/source/pliptool/plip/plipcmd", line 172, in main
    process_pdb(pdbpath, config.OUTPATH, outputprefix=outputprefix)
  File "/home/user/bin/source/pliptool/plip/plipcmd", line 68, in process_pdb
    mol.characterize_complex(ligand)
  File "/home/user/bin/source/pliptool/plip/modules/preparation.py", line 1390, in characterize_complex
    lig_obj = Ligand(self, ligand)
  File "/home/user/bin/source/pliptool/plip/modules/preparation.py", line 1001, in __init__
    descvalues = self.molecule.calcdesc()
  File "/usr/lib/python2.7/dist-packages/pybel.py", line 361, in calcdesc
    raise ValueError("%s is not a recognised Open Babel descriptor type" % descname)
ValueError: @w7 is not a recognised Open Babel descriptor type

#System set-up:
Python 2.7.2
Open Babel version: 2.3.2
Ubuntu 16.04 LTS

**Comment by ssalentin** [comment]
Please check your OpenBabel installation. It might be that your Python bindings don't match the installed OpenBabel version.
See [here](https://openbabel.org/docs/dev/Installation/install.html#install-binaries) for installation instructions.
Question was also added to the new FAQ in the README.md .
